add setLiquiditySourceLsps2
LtbLightning/ldk-node-rn pull request #15
Opened 2024-10-03 13:37 UTC by BitcoinZavior

2024-10-03 17:15 UTC, kumulynja commented
`setLiquiditySourceLsps2` is working now 👍 
But `receiveViaJitChannel` and `receiveVariableAmountViaJitChannel` are missing to be able to use JIT channels completely.

2024-10-05 00:09 UTC, BitcoinZavior commented
> receiveVariableAmountViaJitChannel

Please check now

2024-10-08 13:52 UTC, kumulynja requested changes

2024-10-08 13:52 UTC, kumulynja commented on src/classes/Node.ts
> +  async receiveViaJitChannel(amountMsat: number, description: string, expirySecs: number): Promise<string> {
`receiveViaJitChannel` was already available in the file and class, see line 249. So I think this has to be removed again.

2024-10-08 13:52 UTC, kumulynja commented on src/classes/NativeLoader.ts
> -  bolt11Payment(nodeId: string): any;
`bolt11Payment` didn't had to be removed I think. So should be added back.

2024-10-17 23:59 UTC, BitcoinZavior commented on src/classes/Node.ts
> +  async receiveViaJitChannel(amountMsat: number, description: string, expirySecs: number): Promise<string> {
Done

2024-10-17 23:59 UTC, BitcoinZavior commented on src/classes/NativeLoader.ts
> -  bolt11Payment(nodeId: string): any;
Done

2024-10-17 23:59 UTC, merged